// export enum _NotificationType {
//   ACCOUNT_APPROVED = 1,
//   ACCOUNT_UNBLOCKED = 2,
//   ACCOUNT_BLOCKED = 3,
//   SUPPORT_TICKET_NEW_REPLY = 4,
//   SUPPORT_TICKET_MERCHANT_RECEIVED = 5,
//   SUPPORT_TICKET_RESOLVED = 6,
//   ACCOUNT_PENDING_APPROVAL = 7,
//   SUPPORT_TICKET_ADMIN_RECEIVED = 8,
//   SUPPORT_TICKET_ADMIN_RESOLVED = 9,
// }

export enum NotificationType {
  SUPPORT_TICKET_ADMIN_RECEIVED = 1,
  SUPPORT_TICKET_ADMIN_RESOLVED = 2,
  ACCOUNT_APPROVED = 3,
  ACCOUNT_UNBLOCKED = 4,
  ACCOUNT_BLOCKED = 5,
  SUPPORT_TICKET_NEW_REPLY = 6,
  SUPPORT_TICKET_MERCHANT_RECEIVED = 7,
  SUPPORT_TICKET_RESOLVED = 8,
  ACCOUNT_PENDING_APPROVAL = 9,
  SUPPORT_TICKET_RESOLVED_BY_ADMIN = 10,
}
