import Sidebars from "@/components/consumer/Sidebar/";
import Animate from "@/components/common/Animate";
import Footer from "@/components/common/Footer/Footer";
import Header from "@/components/common/Header/Header";
import { Metadata } from "next";
import StripeElementWrapper from "@/components/consumer/PaymentMethods/StripeElementWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StripeElementWrapper>
      <main className="flex flex-col justify-center overflow-x-clip px-1">
        <Header className="container sticky top-0 z-[5] bg-white" />
        <div className=" container ">
          <div className="md:flex lg:gap-8">
            <div className="  lg:w-[249px] lg:pt-[26px]">
              <Sidebars />
            </div>
            <Animate className="flex-grow ">{children}</Animate>
          </div>
        </div>
        <Footer />
      </main>
    </StripeElementWrapper>
  );
}
