import { IMearchantStoreProfile } from "@/components/merchant/MyAccount/types";

export const initialStoreProfile: IMearchantStoreProfile = {
  id: 0,
  merchant_id: 0,
  name: "",
  description: "",
  email: "",
  phone: "",
  website: "",
  social_media_website: "",
  twitter: "",
  instagram: "",
  linkedin: "",
  facebook: "",
  status: "",
  about_store: "",
  feature_image: {
    id: 0,
    filename: "",
    reference_id: 0,
    type: 0,
    action_by: 0,
    medium_path: "",
    path: "",
    thumbnail_path: "",
  },
  address: "",
  action_by: "",
  last_updated_by: "",
  created_at: "",
  updated_at: "",
  gallery: [],
  logo: {
    id: 0,
    filename: "",
    reference_id: 0,
    type: 0,
    action_by: 0,
    medium_path: "",
    path: "",
    thumbnail_path: "",
  },
};
